PRCP ID, Identified Features
1000019745, "$ Crisis Add On Pd, % $ Pd Crisis Add On, Crisis Add On Pt Cnt, Crisis Add On Vst Cnt"
1000040019, "$ Diff State Treat Pd, % $ Pd Diff State Treat, Diff State Treat Pt Cnt, Diff State Treat Vst Cnt, $ Non-MD CPT Pd, % $ Pd Non-MD CPT, Non-MD CPT Pt Cnt, Non-MD CPT Vst Cnt, State (FL), Provider Type (MD)"
1000057290, "Psychother Add On E/M Pt Cnt, Psychother Add On E/M Vst Cnt, $ Psychother Add On E/M Pd, % $ Pd Psychother Add On E/M"
1000061733, "$ Non-MD CPT Pd, % $ Pd Non-MD CPT, Non-MD CPT Pt Cnt, Non-MD CPT Vst Cnt, Improvement noted (possibly affecting $ High Cost E/M Pd, % $ Pd High Cost E/M, High Cost E/M Pt Cnt, High Cost E/M Vst Cnt)"
1000089256, "$ >8 Hour/Day Days Pd, % Days >8 Hour/Day"
1000110101, "Provider Type (PHD), Top HCPC (H0015)"
1000111750, "No recent billing (possibly affecting $ Tot Pd, % $ Pd Tot, Tot Days Pt Seen, Tot Vst Cnt)"
1000111835, "Psych testing, % Pt Psychother Add On E/M, Psychother Add On E/M Pt Cnt, State (WI)"
1000134212, "Psych testing, % Pt Crisis Add On, Crisis Add On Pt Cnt, Case open (possibly affecting $ Tot Pd, % $ Pd Tot, Tot Days Pt Seen, Tot Vst Cnt)"
1000146589, "Case status open (possibly affecting $ Tot Pd, % $ Pd Tot, Tot Days Pt Seen, Tot Vst Cnt)"
1000168187, "Billing patterns, Add ons and EMS (possibly affecting $ Non-MD CPT Pd, % $ Pd Non-MD CPT, Non-MD CPT Pt Cnt, Non-MD CPT Vst Cnt, $ Psychother Add On E/M Pd, % $ Pd Psychother Add On E/M, Psychother Add On E/M Pt Cnt, Psychother Add On E/M Vst Cnt)"
1000176304, "Out of scope for PM-ASAM (possibly affecting $ Tot Pd, % $ Pd Tot, Tot Days Pt Seen, Tot Vst Cnt)"
1000207812, "Non MD codes, Potential incident to (possibly affecting $ Non-MD CPT Pd, % $ Pd Non-MD CPT, Non-MD CPT Pt Cnt, Non-MD CPT Vst Cnt)"
1000208203, "Primarily IP services (possibly affecting $ Tot Pd, % $ Pd Tot, Tot Days Pt Seen, Tot Vst Cnt)"
1000210248, "High complexity e/m, Non traditional MD, Telemental health services (possibly affecting $ High Cost E/M Pd, % $ Pd High Cost E/M, High Cost E/M Pt Cnt, High Cost E/M Vst Cnt, Provider Type (MD))"
1000211683, "Mostly telehealth, Group reviewed (possibly affecting $ Tot Pd, % $ Pd Tot, Tot Days Pt Seen, Tot Vst Cnt, Provider Type (MSW))"
1000220734, "MD in GA, Telehealth, Long days (possibly affecting State (GA), Provider Type (MD), % Days >8 Hour/Day)"
1000221952, "Minimal non-MD codes, Individual PPA (possibly affecting $ Non-MD CPT Pd, % $ Pd Non-MD CPT, Non-MD CPT Pt Cnt, Non-MD CPT Vst Cnt)"
1000222531, "Longer days, Supervisory Protocol (possibly affecting % Days >8 Hour/Day, Provider Type (PHD))"
1000226224, "MD RI, Multidisciplinary group, IP (possibly affecting State (RI), Provider Type (MD))"
1000230849, "Information sent to PS (possibly affecting multiple features)"
1000233953, "Billing for others, Large practice (possibly affecting $ X-billing Pd, % $ Pd X-billing, X-billing Pt Cnt, X-billing Vst Cnt)"
1000236938, "MD in RI, Addressed for prior provider (possibly affecting State (RI), Provider Type (MD))"
1000242087, "EDW claims, MD in GA, Group open (possibly affecting State (GA), Provider Type (MD))"
1000247842, "MD in FL, Provider doing mostly E/M (possibly affecting State (FL), Provider Type (MD))"
1000249243, "Flag in place, Multiple TINS (possibly affecting multiple features)"
1000249319, "MD RI, Recovery Connections, Lifespan PPA (possibly affecting State (RI), Provider Type (MD))"
1000250184, "MD in FL, Select provider (possibly affecting State (FL), Provider Type (MD))"
1000251675, "Flag placed, Case should be closed (possibly affecting multiple features)"
1000251748, "MD in FL, Elite DNA (possibly affecting State (FL), Provider Type (MD))"
1000255202, "MD in FL, Primarily IP (possibly affecting State (FL), Provider Type (MD))"
1000257540, "MD in WI, Group PPA (possibly affecting State (WI), Provider Type (MD))"
1000259428, "Closed current case (possibly affecting multiple features)"
1000263971, "ORC / auditing (possibly affecting multiple features)"
1000264204, "ORC, Case open (possibly affecting multiple features)"
1000268046, "Staffed with AVP and mgr (possibly affecting multiple features)"
1000272889, "Open also to Gayna, ORC scheduled (possibly affecting multiple features)"
1000273339, "Open to Gayna, ORC PNI referral (possibly affecting multiple features)"
1000275955, "MD in AL, Telehealth (possibly affecting State (AL), Provider Type (MD))"
1000281799, "MD, ORC conducted (possibly affecting Provider Type (MD))"
1000282394, "Conc tx, IP work (possibly affecting multiple features)"
1000286450, "ORC in Feb 23, Incident to only (possibly affecting multiple features)"
1000287538, "Case had a tip, Sent to network (possibly affecting multiple features)"
1000288616, "PhD in MO, ORC necessary (possibly affecting State (MO), Provider Type (PHD))"
1000290491, "MD in MO, All E/Ms and TMS (possibly affecting State (MO), Provider Type (MD))"
1000291082, "States and add-on codes, 2 TINS (possibly affecting multiple features)"
1000292943, "Needs monitoring (possibly affecting multiple features)"
1000293325, "Triggered for cctx and states (possibly affecting multiple features)"
1000296322, "99.8% billing at 3B, No patterns of concern (possibly affecting multiple features)"
1000302230, "Flag requested (possibly affecting multiple features)"
1000302979, "NB has case, PNI referral (possibly affecting multiple features)"
1000308995, "Triggered for add ons (possibly affecting multiple features)"
1000309406, "Triggered for states (possibly affecting multiple features)"
1000309849, "ORC, Acknowledged billing (possibly affecting multiple features)"
1000309870, "ORC was being scheduled (possibly affecting multiple features)"
1000312947, "2I in RI, Check with network (possibly affecting State (RI))"
1000342543, "Re-ran PPAs, EDW only (possibly affecting multiple features)"
1000347454, "Billing is primarily HCPC (possibly affecting $ HCPC Pd, % $ Pd HCPC, HCPC Pt Cnt, HCPC Vst Cnt)"
